"""
Test-local stubs for the generated ROS2 message packages (`movement_interfaces`,
`system_interfaces`) that the obstacle entity modules import at module scope but
never actually need for their pure-python geometry logic.

These modules are generated by rosidl and require a sourced ROS2 environment to
import for real. Since this test suite only exercises plain-python behavior
(distance/collision/adaptDestination math), we install lightweight fake modules
into sys.modules *before* any `new_movement` package code is imported, so the
`from movement_interfaces.msg import X` / `from system_interfaces.msg import X`
statements resolve without requiring rclpy/rosidl to be installed.

This file only affects test collection under this directory (pytest conftest
scoping) and does not modify any source files.
"""
import sys
import types


def _ensure_module(name):
    if name in sys.modules:
        return sys.modules[name]
    mod = types.ModuleType(name)
    sys.modules[name] = mod
    if "." in name:
        parent_name, child_name = name.rsplit(".", 1)
        parent = _ensure_module(parent_name)
        setattr(parent, child_name, mod)
    return mod


class _FakeMsg:
    """Generic stand-in for a rosidl-generated message class."""

    def __init__(self, *args, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)


def _install_fake_msg_classes(module_name, class_names):
    mod = _ensure_module(module_name)
    for class_name in class_names:
        if not hasattr(mod, class_name):
            fake_cls = type(class_name, (_FakeMsg,), {})
            setattr(mod, class_name, fake_cls)


_install_fake_msg_classes(
    "movement_interfaces.msg",
    [
        "Vector2D",
        "Trajectory",
        "TrajectorySegment",
        "MotionPath",
        "MotionPrimitive",
    ],
)

_install_fake_msg_classes(
    "system_interfaces.msg",
    [
        "VisionGeometry",
    ],
)
