"""
Test-only mocks for generated ROS2 message/service modules.

apiNode imports message and service types from `movement_interfaces.msg`
and `system_interfaces.msg`/`system_interfaces.srv`/`std_srvs.srv`
(generated by rosidl at colcon-build time). None of these unit tests need
real (de)serialization, so we stub the modules here rather than requiring
a full ROS2 build environment to run these tests -- the same pattern
already used in src/referee/test/conftest.py and the new_movement test
suite.
"""

import sys
from unittest.mock import MagicMock


def _install(name):
    if name not in sys.modules:
        sys.modules[name] = MagicMock(name=name)
    return sys.modules[name]


_install("movement_interfaces")
movement_msg = _install("movement_interfaces.msg")

system_interfaces = _install("system_interfaces")
system_interfaces.msg = _install("system_interfaces.msg")
system_interfaces.srv = _install("system_interfaces.srv")

_install("std_srvs")
_install("std_srvs.srv")

std_msgs = _install("std_msgs")
std_msgs.msg = _install("std_msgs.msg")


class _GUIRobot:
    def __init__(self):
        self.id = None
        self.name = None
        self.address = None
        self.kp = None
        self.ki = None
        self.kd = None


class _GUIMessage:
    def __init__(self):
        self.is_field_side_left = None
        self.is_team_color_yellow = None
        self.is_play_pressed = None
        self.robots = []
        self.robot_count = None


# create_message() builds real GUIMessage/GUIRobot instances and appends to
# msg.robots, so these need to behave like plain mutable objects rather than
# auto-vivifying MagicMocks.
sys.modules["system_interfaces.msg"].GUIMessage = _GUIMessage
sys.modules["system_interfaces.msg"].GUIRobot = _GUIRobot


class _Vector2D:
    def __init__(self):
        self.x = 0.0
        self.y = 0.0


class _PlanningOptions:
    def __init__(self):
        self.avoid_penalty_area = False
        self.avoid_center_area = False
        self.avoid_ball = False
        self.aggressiveness = 0.0


class _MovementCommand:
    def __init__(self):
        self.robot_id = None
        self.target_pos = _Vector2D()
        self.target_vel = _Vector2D()
        self.planning_options = _PlanningOptions()


class _MovementCommandArray:
    def __init__(self):
        self.commands = []


# A MagicMock class returns the *same* instance on every call, which would collapse
# every robot's command into one object. These need distinct instances.
movement_msg.MovementCommand = _MovementCommand
movement_msg.MovementCommandArray = _MovementCommandArray
