"""
Test-only mocks for generated ROS2 message modules.

The local_planner code imports message types from `movement_interfaces.msg`
and `system_interfaces.msg` (generated by rosidl at colcon-build time) purely
for `to_msg`/`from_msg` (de)serialization helpers. None of the local_planner
unit tests exercise that (de)serialization path, so we stub the modules out
here rather than requiring a full ROS2 build environment to run these tests.
"""

import sys
from unittest.mock import MagicMock

if "movement_interfaces" not in sys.modules:
    _mock_movement_interfaces = MagicMock(name="movement_interfaces")
    sys.modules["movement_interfaces"] = _mock_movement_interfaces
    sys.modules["movement_interfaces.msg"] = _mock_movement_interfaces.msg

if "system_interfaces" not in sys.modules:
    _mock_system_interfaces = MagicMock(name="system_interfaces")
    sys.modules["system_interfaces"] = _mock_system_interfaces
    sys.modules["system_interfaces.msg"] = _mock_system_interfaces.msg



# `SolverConfig` (new_movement/local_planner/solver/solver_config.py) declares
# dataclass fields such as `max_velocity: Vector2D = Vector2D(2000.0, -2000.0)`.
# `Vector2D` is a plain (non-frozen) `@dataclass`, so Python auto-generates
# `__eq__` and, per data-model rules, sets `__hash__ = None` unless a custom
# hash is provided -- making it unhashable. Since Python 3.11, the stdlib
# `dataclasses` module refuses to accept an unhashable object as a field
# default (it's a safety check against accidental shared-mutable defaults,
# such as lists), raising `ValueError: mutable default ... not allowed`
# purely at import time. This repo targets ROS2 environments that pin
# Python 3.10 (see install/*/local/lib/python3.10/...), where this check
# does not exist, so the source is not actually broken there -- it just
# can't be imported unmodified on the Python 3.12 interpreter available in
# this test environment. Since source files must not be modified for this
# test migration, we patch in a real `__hash__` for `Vector2D` here,
# test-side only, before anything imports the local_planner package.
from utils.math_util import Vector2D as _Vector2D

if _Vector2D.__hash__ is None:
    _Vector2D.__hash__ = lambda self: hash((self.x, self.y))


import pytest

from new_movement.local_planner import InformedSampler, TrajectoryGenerator


@pytest.fixture
def generator():
    return TrajectoryGenerator()


@pytest.fixture
def sampler():
    return InformedSampler(field_length=12000, field_width=9000, max_velocity=3000)
