"""
Test-only mocks for generated ROS2 message modules.

The local_planner code imports message types from `movement_interfaces.msg` and
`system_interfaces.msg` (generated by rosidl at colcon-build time) purely for
`to_msg`/`from_msg` helpers. None of these tests exercise that path, so the modules are
stubbed out here rather than requiring a full ROS2 build to run them.
"""

import random
import sys
from unittest.mock import MagicMock

import numpy as np
import pytest

if "movement_interfaces" not in sys.modules:
    _mock_movement_interfaces = MagicMock(name="movement_interfaces")
    sys.modules["movement_interfaces"] = _mock_movement_interfaces
    sys.modules["movement_interfaces.msg"] = _mock_movement_interfaces.msg

if "system_interfaces" not in sys.modules:
    _mock_system_interfaces = MagicMock(name="system_interfaces")
    sys.modules["system_interfaces"] = _mock_system_interfaces
    sys.modules["system_interfaces.msg"] = _mock_system_interfaces.msg

from new_movement.local_planner import InformedSampler, TrajectoryGenerator  # noqa: E402


@pytest.fixture(autouse=True)
def deterministic_sampling():
    """
    The solver samples from numpy's global RNG, so without this a test's result depends
    on how many samples the tests before it happened to draw.
    """
    np.random.seed(20260827)
    random.seed(20260827)


@pytest.fixture
def generator():
    return TrajectoryGenerator()


@pytest.fixture
def sampler():
    return InformedSampler(field_length=12000, field_width=9000, max_velocity=3000)
